name: Vericode Pylint Check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  vericode-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install vericode
        run: pip install vericode

      - name: Run vericode (pylint)
        run: vericode -t pylint -s . --scores-less-than 8
